import React from 'react';
import { AlertCircle, CheckCircle2, ShieldAlert, ExternalLink, Tag } from 'lucide-react';
import ThreatBadge from './ThreatBadge';

function SectionCard({ children, accent = '#ef4444', title, badge, className = '' }) {
  return (
    <div
      className={`rounded-2xl overflow-hidden ${className}`}
      style={{
        border: `1px solid ${accent}22`,
        boxShadow: `0 0 20px ${accent}08`,
      }}
    >
      {title && (
        <div
          className="flex items-center justify-between px-5 py-4"
          style={{
            background: `linear-gradient(90deg, ${accent}08, transparent)`,
            borderBottom: `1px solid ${accent}15`,
          }}
        >
          <div className="flex items-center gap-2">{title}</div>
          {badge}
        </div>
      )}
      <div className="p-5 space-y-4" style={{ background: '#0a0f1e' }}>{children}</div>
    </div>
  );
}

function InfoCell({ label, value, valueColor = '#e2e8f0' }) {
  return (
    <div
      className="rounded-xl p-3"
      style={{ background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.06)' }}
    >
      <span
        className="block text-[9px] font-bold uppercase tracking-widest mb-1"
        style={{ color: '#334155', fontFamily: 'JetBrains Mono, monospace' }}
      >
        {label}
      </span>
      <span className="text-sm font-bold font-mono" style={{ color: valueColor }}>{value}</span>
    </div>
  );
}

export default function EvidenceCard({ domainAnalysis, languageAnalysis, urlAnalysis, senderAnalysis, attachmentAnalysis }) {
  const hasContent = domainAnalysis?.is_brand_impersonation || languageAnalysis?.detected_keywords?.length > 0 || urlAnalysis?.urls?.length > 0 || attachmentAnalysis?.attachments?.length > 0;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 mb-1">
          <ShieldAlert className="w-5 h-5 text-red-400" />
          <h2 className="text-xl font-bold text-white">Why is this email suspicious?</h2>
        </div>
        <p className="text-xs font-mono" style={{ color: '#475569' }}>
          Transparent evidence generated by PhishLens Explainable Forensic Engine
        </p>
      </div>

      {!hasContent && (
        <div
          className="rounded-2xl p-8 text-center"
          style={{ background: '#0a0f1e', border: '1px solid rgba(34,197,94,0.2)' }}
        >
          <CheckCircle2 className="w-10 h-10 text-emerald-400 mx-auto mb-3" />
          <p className="text-white font-bold">No threat indicators found</p>
          <p className="text-sm text-slate-400 mt-1">This email passed all forensic analysis checks</p>
        </div>
      )}

      <div className="space-y-4">
        {/* 1. Brand Impersonation */}
        {domainAnalysis?.is_brand_impersonation && (
          <SectionCard
            accent="#ef4444"
            title={
              <>
                <span
                  className="px-2 py-1 rounded text-[10px] font-bold font-mono uppercase"
                  style={{ background: 'rgba(239,68,68,0.15)', color: '#f87171', border: '1px solid rgba(239,68,68,0.3)' }}
                >
                  Brand Impersonation
                </span>
                <h3 className="text-sm font-bold text-white">Deceptive Brand Impersonation Attack</h3>
              </>
            }
            badge={<ThreatBadge severity="CRITICAL" size="sm" />}
          >
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <InfoCell label="Suspicious Domain" value={domainAnalysis.domain} valueColor="#f87171" />
              <InfoCell label="Legitimate Brand Target" value={domainAnalysis.detected_brand} valueColor="#34d399" />
              <InfoCell label="Similarity Score" value={`${domainAnalysis.brand_similarity_score}% Match`} valueColor="#fbbf24" />
            </div>
            <p
              className="text-xs leading-relaxed rounded-xl p-3"
              style={{ background: 'rgba(0,0,0,0.25)', border: '1px solid rgba(255,255,255,0.05)', color: '#cbd5e1' }}
            >
              <strong className="text-white">Explanation: </strong>
              The domain <code className="px-1 py-0.5 rounded text-xs" style={{ background: 'rgba(239,68,68,0.15)', color: '#fca5a5' }}>{domainAnalysis.domain}</code> closely
              resembles <strong className="text-emerald-400">{domainAnalysis.detected_brand}</strong> using character
              substitution (homoglyph/typosquatting) to deceive recipients into trusting the sender.
            </p>
          </SectionCard>
        )}

        {/* 2. NLP Urgency Language */}
        {languageAnalysis?.detected_keywords?.length > 0 && (
          <SectionCard
            accent="#f97316"
            title={
              <>
                <span
                  className="px-2 py-1 rounded text-[10px] font-bold font-mono uppercase"
                  style={{ background: 'rgba(249,115,22,0.15)', color: '#fb923c', border: '1px solid rgba(249,115,22,0.3)' }}
                >
                  Urgency Language
                </span>
                <h3 className="text-sm font-bold text-white">Coercive Psychological Pressure & Urgency</h3>
              </>
            }
            badge={<ThreatBadge severity={languageAnalysis.risk_level} size="sm" />}
          >
            <div>
              <p
                className="text-[10px] font-bold uppercase tracking-wider mb-2 font-mono"
                style={{ color: '#475569' }}
              >
                Detected Threat Keywords
              </p>
              <div className="flex flex-wrap gap-2">
                {languageAnalysis.detected_keywords.map((kw, idx) => (
                  <span
                    key={idx}
                    className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-mono font-bold"
                    style={{
                      background: 'rgba(239,68,68,0.1)',
                      color: '#fca5a5',
                      border: '1px solid rgba(239,68,68,0.25)',
                    }}
                  >
                    <Tag className="w-3 h-3" />
                    "{kw}"
                  </span>
                ))}
              </div>
            </div>
            <p
              className="text-xs leading-relaxed rounded-xl p-3"
              style={{ background: 'rgba(0,0,0,0.25)', border: '1px solid rgba(255,255,255,0.05)', color: '#cbd5e1' }}
            >
              <strong className="text-white">Explanation: </strong>
              The message creates artificial panic by threatening account suspension and demanding immediate action. This psychological manipulation forces recipients to act hastily without verifying authenticity.
            </p>
          </SectionCard>
        )}

        {/* 3. Suspicious URLs */}
        {urlAnalysis?.urls?.length > 0 && (
          <SectionCard
            accent="#6366f1"
            title={
              <>
                <span
                  className="px-2 py-1 rounded text-[10px] font-bold font-mono uppercase"
                  style={{ background: 'rgba(99,102,241,0.15)', color: '#a5b4fc', border: '1px solid rgba(99,102,241,0.3)' }}
                >
                  Suspicious URLs ({urlAnalysis.total_urls})
                </span>
                <h3 className="text-sm font-bold text-white">Deceptive Link Inspection</h3>
              </>
            }
            badge={<ThreatBadge severity={urlAnalysis.risk_level} size="sm" />}
          >
            <div className="space-y-3">
              {urlAnalysis.urls.map((u, idx) => (
                <div
                  key={idx}
                  className="rounded-xl p-4 space-y-2"
                  style={{
                    background: 'rgba(0,0,0,0.3)',
                    border: '1px solid rgba(255,255,255,0.06)',
                  }}
                >
                  <div className="flex items-center justify-between gap-3">
                    <span
                      className="text-xs font-mono font-bold break-all flex items-center gap-1"
                      style={{ color: '#f87171' }}
                    >
                      <ExternalLink className="w-3.5 h-3.5 flex-shrink-0" />
                      {u.url}
                    </span>
                    <ThreatBadge severity={u.risk_level} size="sm" />
                  </div>
                  <div
                    className="flex flex-wrap gap-4 text-[11px] pt-2 font-mono"
                    style={{ borderTop: '1px solid rgba(255,255,255,0.05)', color: '#64748b' }}
                  >
                    <span>Protocol: <strong style={{ color: u.protocol === 'HTTP' ? '#f87171' : '#4ade80' }}>{u.protocol}</strong></span>
                    <span>Domain: <strong className="text-slate-300">{u.domain}</strong></span>
                    <span>Path: <strong style={{ color: '#fbbf24' }}>{u.path || '/'}</strong></span>
                    {u.is_brand_impersonation && <span style={{ color: '#f87171', fontWeight: 700 }}>● Brand Impersonation</span>}
                  </div>
                </div>
              ))}
            </div>
          </SectionCard>
        )}

        {/* 4. Attachment Risk */}
        {attachmentAnalysis?.attachments?.length > 0 && (
          <SectionCard
            accent="#a855f7"
            title={
              <>
                <span
                  className="px-2 py-1 rounded text-[10px] font-bold font-mono uppercase"
                  style={{ background: 'rgba(168,85,247,0.15)', color: '#c4b5fd', border: '1px solid rgba(168,85,247,0.3)' }}
                >
                  Attachment Risk
                </span>
                <h3 className="text-sm font-bold text-white">Attachment Forensics</h3>
              </>
            }
            badge={<ThreatBadge severity={attachmentAnalysis.risk_level} size="sm" />}
          >
            <div className="space-y-2">
              {attachmentAnalysis.attachments.map((att, idx) => (
                <div
                  key={idx}
                  className="rounded-xl p-3 flex items-center justify-between"
                  style={{
                    background: 'rgba(0,0,0,0.3)',
                    border: '1px solid rgba(255,255,255,0.06)',
                  }}
                >
                  <div>
                    <span className="text-sm font-bold font-mono text-white block">{att.filename}</span>
                    <span className="text-xs font-mono" style={{ color: '#64748b' }}>
                      Type: {att.file_type} · Size: {Math.round((att.size_bytes || 0) / 1024)} KB
                    </span>
                  </div>
                  <ThreatBadge severity={att.risk_level} size="sm" />
                </div>
              ))}
            </div>
          </SectionCard>
        )}
      </div>
    </div>
  );
}
