import React from 'react';
import { AlertCircle, CheckCircle2, ShieldAlert, Sparkles, ExternalLink, Tag } from 'lucide-react';
import ThreatBadge from './ThreatBadge';

export default function EvidenceCard({ domainAnalysis, languageAnalysis, urlAnalysis, senderAnalysis, attachmentAnalysis }) {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-red-400" />
            <span>Why is this email suspicious?</span>
          </h2>
          <p className="text-xs text-slate-400 font-mono mt-0.5">
            Transparent evidence generated by PhishLens Explainable Forensic Engine
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4">
        
        {/* 1. Brand Impersonation Evidence */}
        {domainAnalysis?.is_brand_impersonation && (
          <div className="glass-panel glass-card-critical rounded-xl p-5 border border-red-500/30 space-y-3">
            <div className="flex items-center justify-between border-b border-red-500/20 pb-3">
              <div className="flex items-center gap-2">
                <span className="p-1.5 rounded bg-red-500/20 text-red-400 font-bold font-mono text-xs">
                  🔴 BRAND IMPERSONATION
                </span>
                <h3 className="text-sm font-bold text-white">Deceptive Brand Impersonation Attack</h3>
              </div>
              <ThreatBadge severity="CRITICAL" size="sm" />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs font-mono">
              <div className="bg-slate-950/80 p-3 rounded-lg border border-slate-800">
                <span className="text-slate-500 text-[10px] block uppercase font-bold">Suspicious Domain</span>
                <span className="text-red-400 font-bold text-sm">{domainAnalysis.domain}</span>
              </div>
              <div className="bg-slate-950/80 p-3 rounded-lg border border-slate-800">
                <span className="text-slate-500 text-[10px] block uppercase font-bold">Legitimate Brand Target</span>
                <span className="text-emerald-400 font-bold text-sm">{domainAnalysis.detected_brand}</span>
              </div>
              <div className="bg-slate-950/80 p-3 rounded-lg border border-slate-800">
                <span className="text-slate-500 text-[10px] block uppercase font-bold">Similarity Ratio</span>
                <span className="text-amber-400 font-bold text-sm">{domainAnalysis.brand_similarity_score}% Match</span>
              </div>
            </div>

            <p className="text-xs text-slate-300 leading-relaxed bg-slate-950/50 p-3 rounded-lg border border-slate-800/60">
              <strong className="text-white">Explanation:</strong> The domain <code className="bg-slate-900 px-1 py-0.5 rounded text-red-300">{domainAnalysis.domain}</code> closely resembles the official brand <strong className="text-emerald-400">{domainAnalysis.detected_brand}</strong> and uses character substitution (homoglyph/typosquatting) to deceive recipients into trusting the sender.
            </p>
          </div>
        )}

        {/* 2. Urgency & NLP Threat Language */}
        {languageAnalysis?.detected_keywords?.length > 0 && (
          <div className="glass-panel glass-card-high rounded-xl p-5 border border-orange-500/30 space-y-3">
            <div className="flex items-center justify-between border-b border-orange-500/20 pb-3">
              <div className="flex items-center gap-2">
                <span className="p-1.5 rounded bg-orange-500/20 text-orange-400 font-bold font-mono text-xs">
                  🟠 URGENCY LANGUAGE
                </span>
                <h3 className="text-sm font-bold text-white">Coercive Psychological Pressure & Urgency</h3>
              </div>
              <ThreatBadge severity={languageAnalysis.risk_level} size="sm" />
            </div>

            <div>
              <span className="text-xs font-mono text-slate-400 font-bold uppercase block mb-2">Detected Threat Badges:</span>
              <div className="flex flex-wrap gap-2">
                {languageAnalysis.detected_keywords.map((kw, idx) => (
                  <span key={idx} className="px-2.5 py-1 rounded-md text-xs font-mono font-bold bg-red-500/20 text-red-300 border border-red-500/40 flex items-center gap-1">
                    <Tag className="w-3 h-3 text-red-400" />
                    "{kw}"
                  </span>
                ))}
              </div>
            </div>

            <p className="text-xs text-slate-300 leading-relaxed bg-slate-950/50 p-3 rounded-lg border border-slate-800/60">
              <strong className="text-white">Explanation:</strong> The message creates artificial panic by threatening account suspension and demanding immediate action. This psychological manipulation forces recipients to act hastily without verifying authenticity.
            </p>
          </div>
        )}

        {/* 3. Suspicious URL Analysis */}
        {urlAnalysis?.urls?.length > 0 && (
          <div className="glass-panel rounded-xl p-5 border border-slate-800 space-y-3">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2">
                <span className="p-1.5 rounded bg-cyan-500/20 text-cyan-400 font-bold font-mono text-xs">
                  🔴 SUSPICIOUS URLS ({urlAnalysis.total_urls})
                </span>
                <h3 className="text-sm font-bold text-white">Deceptive Link Inspection</h3>
              </div>
              <ThreatBadge severity={urlAnalysis.risk_level} size="sm" />
            </div>

            <div className="space-y-2">
              {urlAnalysis.urls.map((u, idx) => (
                <div key={idx} className="bg-slate-950 p-3 rounded-lg border border-slate-800/80 space-y-1.5 font-mono text-xs">
                  <div className="flex items-center justify-between">
                    <span className="text-red-400 font-bold break-all flex items-center gap-1">
                      <ExternalLink className="w-3.5 h-3.5" />
                      {u.url}
                    </span>
                    <ThreatBadge severity={u.risk_level} size="sm" />
                  </div>
                  <div className="flex flex-wrap gap-3 text-[11px] text-slate-400 pt-1 border-t border-slate-900">
                    <span>Protocol: <strong className={u.protocol === 'HTTP' ? 'text-red-400' : 'text-emerald-400'}>{u.protocol}</strong></span>
                    <span>Domain: <strong className="text-slate-200">{u.domain}</strong></span>
                    <span>Path: <strong className="text-amber-400">{u.path || '/'}</strong></span>
                    {u.is_brand_impersonation && <span className="text-red-400 font-bold">● Brand Impersonation</span>}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* 4. Attachments Evidence */}
        {attachmentAnalysis?.attachments?.length > 0 && (
          <div className="glass-panel rounded-xl p-5 border border-slate-800 space-y-3">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2">
                <span className="p-1.5 rounded bg-purple-500/20 text-purple-400 font-bold font-mono text-xs">
                  📎 ATTACHMENT RISK
                </span>
                <h3 className="text-sm font-bold text-white">Attachment Forensics</h3>
              </div>
              <ThreatBadge severity={attachmentAnalysis.risk_level} size="sm" />
            </div>

            <div className="space-y-2">
              {attachmentAnalysis.attachments.map((att, idx) => (
                <div key={idx} className="bg-slate-950 p-3 rounded-lg border border-slate-800 font-mono text-xs flex items-center justify-between">
                  <div>
                    <span className="text-white font-bold block">{att.filename}</span>
                    <span className="text-[11px] text-slate-400">Type: {att.file_type} | Size: {Math.round((att.size_bytes || 0) / 1024)} KB</span>
                  </div>
                  <ThreatBadge severity={att.risk_level} size="sm" />
                </div>
              ))}
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
